# Список слів, при зустрічанні яких парсер припиняє подальше сканування сайту.
# Якщо одне з цих слів знайдене в текстовому вмісті блоку, блок буде заблоковано,
# і парсер припинить подальшу обробку цього блоку.
ignore_words:
  - 'Обычно микрофобия также сопровождается следующими симптомами'
  - 'Похожие статьи'
  - 'Автор:'

# Список тегів, які будуть видалені, але їх вміст залишиться.
# Наприклад, <div><p>Text</p></div> буде перетворено в <div>Text</div>.
tags_to_remove:
  - 'span'
  - 'div'
  - 'section'
  - 'article'
  - 'noscript'

# Список тегів, які будуть повністю видалені разом з їх вмістом.
# Наприклад, <div><p>Text</p></div> буде перетворено в <div></div>.
tags_to_del:
  - 'head'        # Метадані, стилі
  - 'meta'        # Метадані, опис сайту, автор
  - 'style'       # Вбудовані стилі
  - 'link'        # Зовнішні стилі, шрифти
  - 'script'      # JavaScript-код
  - 'svg'         # Графіка
  - 'use'         # Вставка графічних елементів
  - 'button'      # Кнопки
  - 'form'        # Форми
  - 'aside'       # Бокові панелі
  - 'nav'         # Навігація
  - 'footer'      # Нижній колонтитул
  - 'header'      # Верхній колонтитул
  - 'iframe'      # Вбудовані фрейми
  - 'object'      # Об'єкти, такі як флеш-контент
  - 'embed'       # Вбудовані елементи
  - 'audio'       # Аудіо
  - 'video'       # Відео
  - 'source'      # Джерела для відео або аудіо
  - 'details'     # Розгортаючі елементи
  - 'summary'     # Заголовок для <details>
  - 'address'     # Адреса
  - 'time'        # Тег для часу і дати
  - 'datalist'    # Список даних для <input>
  - 'menu'        # Меню
  - 'dialog'      # Діалоги
  - 'input'

# Якщо встановлено в 1, стилі видаляються з тегів.
# Якщо встановлено в 0, стилі залишаються в тегах.
# При 1: <div>Text</div>
# При 0: <div style="color: red;">Text</div>
# Уточнення: Якщо це виставлено в 1 то одступи початок тексту зверх зниз і подібне пропаде!!! .
remove_style_attributes: 0

# Таймаут: час (в секундах), протягом якого чекаємо відповідь від сервера.
timeout_time: 15

# Атрибути тегів <img>, які використовуються для отримання URL зображень.
# Використовується для заміни відносних URL на абсолютні, враховуючи різні атрибути, які можуть бути використані на різних сайтах.
image_src_attributes:
  - 'data-lazy-src'
  - 'data-src'
  - 'src'
  - 'data-original'
  - 'srcset'

# Список атрибутів, які будуть видалені з тегів.
# Наприклад, 'class', 'id', 'style' тощо.
attributes_to_remove:
  - 'id'
  - 'href'
  - 'class'
  - 'data-lazy-src'
  - 'data-src'
  - 'data-original'
  - 'data-srcset'
  - 'decoding'
  - 'data-lazy-type'
  - 'alt'
  - 'srcset'
#_____________________________________________________________________#
# Якщо встановлено будь-яке значення, відмінне від 0, буде виконано очистку даних перед збереженням.
# Це означає, що з даних будуть видалені всі знаки.
cleaned_data_save: 1

# Якщо встановлено будь-яке значення, відмінне від 0, буде виконано очистку даних перед візуалізацією в Table View.
# Це означає, що з даних будуть видалені всі знаки.
cleaned_data_table_view: 1

now_base_url_image: ''
#_____________________________________________________________________#
# local server
host: 127.0.0.1
port: 8000

#_____________________________________________________________________#
# Мова результатів пошуку
# Можливі значення включають коди мов за стандартом ISO 639-1
# Приклад: 'en' для англійської, 'es' для іспанської тощо
# https://en.wikipedia.org/wiki/List_of_ISO_639_language_codes
lang: 'uk'

# Регіон для фільтрації результатів пошуку
# Можливі значення: коди країн, такі як 'us' для США, 'uk' для Великобританії тощо
# https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2
region: 'ua'

# Налаштування фільтра безпеки Google
# Можливі значення:
# 'active' - активний фільтр безпеки
# 'off' - фільтр безпеки вимкнуто
# 'medium' - середній рівень фільтрації
safe: 'active'